version: "2"
services:
   namenode:
      image: flokkr/hadoop:${VERSION}
      hostname: namenode
      command: ["hdfs", "namenode"]
      ports:
         - 50070:50070
         - 9870:9870
      env_file:
        - config
      environment:
          ENSURE_NAMENODE_DIR: "/tmp/hadoop-hadoop/dfs/name"
   datanode:
      image: flokkr/hadoop:${VERSION}
      command: ["hdfs", "datanode"]
      links:
         - namenode
      env_file:
        - config
   resourcemanager:
      image: flokkr/hadoop:${VERSION}
      hostname: resourcemanager
      command: ["yarn", "resourcemanager"]
      ports:
         - 8088:8088
      env_file:
        - config
      volumes:
        - ./testdata:/opt/testdata
   nodemanager:
      image: flokkr/hadoop:${VERSION}
      command: ["yarn","nodemanager"]
      links:
         - resourcemanager
         - namenode
      env_file:
        - config
